version: "3.8"

services:
  nginx:
    image: "nginx:latest"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
  php:
    build:
      context: dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/laravel
  mysql:
    image: "mysql:latest"
    ports:
      - "3316:3306"
    env_file:
      - env/mysql.env
  composer:
    build:
      context: dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/laravel
#  npm:
#    build:
#      context: dockerfiles
#      dockerfile: npm.dockerfile
#    volumes:
#    - ./src:/var/www/laravel
#composer создан для того, чтоб скачать laravel [docker-compose run composer create-project laravel/laravel .]

#bash: docker exec -it puuuffanddooy-php-1 sh
#npm: